#!/usr/bin/env python3
"""Regenerate static map metadata from archived site folders.

The archive is intentionally static and portable. This script keeps the JSON
files and Netlify subdomain rewrites in sync with top-level folders that contain
an index.html file, without requiring any external packages or network access.
"""

from __future__ import annotations

import hashlib
import html
import json
import math
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
BUBBLES = ROOT / "assets" / "bubbles"
DOMAIN = "possibilitymanagement.xyz"
EXCLUDED_DIRS = {
    ".git",
    ".github",
    ".netlify",
    "_assets",
    "3d-bubble-map",
    "assets",
    "data",
    "netlify",
    "scripts",
}
GENERIC_TITLES = {
    "",
    "forwarding website",
    "website",
    "untitled",
}


def load_json(path: Path, fallback):
    if not path.exists():
        return fallback
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, value) -> None:
    text = json.dumps(value, ensure_ascii=False, indent=2) + "\n"
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)


def site_dirs() -> list[Path]:
    dirs = []
    for path in ROOT.iterdir():
        if not path.is_dir() or path.name in EXCLUDED_DIRS or path.name.startswith("."):
            continue
        if (path / "index.html").is_file():
            dirs.append(path)
    return sorted(dirs, key=lambda p: p.name)


def humanize_slug(slug: str) -> str:
    parts = re.split(r"[-_]+", slug)
    words = []
    for part in parts:
        part = re.sub(r"(?<=\D)(?=\d)|(?<=\d)(?=\D)", " ", part)
        words.append(part)
    return " ".join(words).strip().title() or slug


def extract_title(slug: str, index_html: Path) -> str:
    text = index_html.read_text(encoding="utf-8", errors="ignore")
    match = re.search(r"<title[^>]*>(.*?)</title>", text, re.IGNORECASE | re.DOTALL)
    if not match:
        return humanize_slug(slug)

    title = html.unescape(match.group(1))
    title = re.sub(r"\s+", " ", title).strip()
    title = re.sub(r"\s+(?:on|by)\s+Strikingly\s*$", "", title, flags=re.IGNORECASE)
    title = re.sub(r"\s*[-|]\s*Strikingly\s*$", "", title, flags=re.IGNORECASE)
    if title.strip().lower() in GENERIC_TITLES:
        return humanize_slug(slug)
    return title or humanize_slug(slug)


def fallback_position(slug: str) -> list[float]:
    digest = hashlib.sha256(slug.encode("utf-8")).digest()
    angle_seed = int.from_bytes(digest[:8], "big") / float(1 << 64)
    radius_seed = int.from_bytes(digest[8:16], "big") / float(1 << 64)
    angle = angle_seed * math.tau
    radius = 170 + radius_seed * 340
    x = max(55, min(945, 500 + math.cos(angle) * radius))
    y = max(55, min(945, 500 + math.sin(angle) * radius))
    return [round(x, 2), round(y, 2)]


def has_bubble(slug: str) -> bool:
    return (BUBBLES / f"{slug}.webp").is_file()


def sync_registry(slugs: list[str]) -> list[dict]:
    registry = load_json(DATA / "registry.json", [])
    by_slug = {entry.get("slug"): entry for entry in registry if entry.get("slug")}
    slug_set = set(slugs)

    for slug in slugs:
        entry = by_slug.get(slug)
        if entry is None:
            entry = {
                "slug": slug,
                "title": extract_title(slug, ROOT / slug / "index.html"),
                "tagline": "",
                "url": f"https://{slug}.{DOMAIN}/",
                "live_url": f"https://{slug}.{DOMAIN}/",
                "archive_url": "",
                "image_url": "",
                "also_see": [],
            }
            registry.append(entry)
            by_slug[slug] = entry

        if has_bubble(slug):
            entry.pop("bubble_image", None)
        else:
            entry["bubble_image"] = "assets/bubbles/_fallback.svg"

    return [entry for entry in registry if entry.get("slug") in slug_set]


def sync_manifest(slugs: list[str]) -> dict[str, str]:
    return {slug: f"{slug}/index.html" for slug in slugs}


def sync_layout(slugs: list[str]) -> dict[str, list[float]]:
    layout = load_json(DATA / "layout.json", {})
    return {slug: layout.get(slug) or fallback_position(slug) for slug in slugs}


def write_redirects(slugs: list[str]) -> None:
    lines = [
        "# Generated by scripts/update_map_data.py",
        f"https://www.{DOMAIN}/* https://{DOMAIN}/:splat 301!",
        f"http://www.{DOMAIN}/* https://{DOMAIN}/:splat 301!",
        "",
        "# Slug subdomains rewrite to the matching archived folder.",
    ]
    for slug in slugs:
        lines.append(f"https://{slug}.{DOMAIN}/* /{slug}/:splat 200!")
        lines.append(f"http://{slug}.{DOMAIN}/* /{slug}/:splat 200!")
    lines.append("")
    with (ROOT / "_redirects").open("w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))


def main() -> None:
    slugs = [path.name for path in site_dirs()]
    if not slugs:
        raise SystemExit("No site folders with index.html found")

    DATA.mkdir(exist_ok=True)
    write_json(DATA / "registry.json", sync_registry(slugs))
    write_json(DATA / "archive-manifest.json", sync_manifest(slugs))
    write_json(DATA / "layout.json", sync_layout(slugs))
    write_redirects(slugs)
    print(f"Map data synced for {len(slugs)} site folders.")


if __name__ == "__main__":
    main()
